 <?php
  /*
Template Name: Custom Template
*/
  get_header();
  ?>
 <!-- ======= Services Section ======= -->
 <section id="services" class="services section-bg">
   <div class="container">

     <div class="section-title" data-aos="fade-up">
       <h2>SERVICES</h2>
       <p>As a provider of 3D services, our team offers a range of specialized services related to
         3D computer graphics, modeling, and design. Our services include 3D asset creation, animation,
         virtual and augmented reality development, 3D scanning, and architectural visualization.
         We work closely with our clients to understand their specific needs and provide tailored
         solutions that meet their project requirements. Our team is committed to delivering high-quality
         services that bring their ideas to life, whether it's for gaming, film and animation, product
         design, or other applications.</p>
     </div>

     <!-- <div class="row">
        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in">
          <div class="icon-box icon-box-pink">
            <div class="icon"><img src="<?php echo get_template_directory_uri() ?>/assets/img/icon/3D Asset.png" alt=""></div>
            <h4 class="title"><a href="">3D Assets</a></h4>
            <p class="description">A digital file containing a three-dimensional object or model used in computer graphics, such as video games, virtual reality, or film and animation projects.</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="100">
          <div class="icon-box icon-box-cyan">
            <div class="icon"><img src="<?php echo get_template_directory_uri() ?>/assets/img/icon/AR VR.png" alt=""></div>
            <h4 class="title"><a href="">AR / VR</a></h4>
            <p class="description">Computer technologies that create immersive digital experiences, either by enhancing the real world (AR) or simulating a virtual environment (VR)</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="200">
          <div class="icon-box icon-box-green">
            <div class="icon"><img src="<?php echo get_template_directory_uri() ?>/assets/img/icon/2d.png" alt=""></div>
            <h4 class="title"><a href="">2D to 3D</a></h4>
            <p class="description">Transforming a two-dimensional image or object into a three-dimensional model using specialized software or hardware.</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="300">
          <div class="icon-box icon-box-blue">
            <div class="icon"><img src="<?php echo get_template_directory_uri() ?>/assets/img/icon/3D Scan.png" alt=""></div>
            <h4 class="title"><a href="">3D Scan</a></h4>
            <p class="description">"Creating a digital 3D model of real-world objects or environments using specialized hardware and software."</p>
          </div>
        </div>

      </div> -->

   </div>
 </section><!-- End Services Section -->

 <!-- ======= Features Section ======= -->
 <section id="features" class="features">
   <div class="container">
     <div class="section-title" data-aos="fade-up">
       <h2>What we do</h2>
     </div>


     <div class="row">
       <div class="col-lg-6 mt-2 mb-tg-0 order-2 order-lg-1">
         <ul class="nav nav-tabs flex-column">
           <li class="nav-item" data-aos="fade-up">
             <a class="nav-link active show" data-toggle="tab" href="#tab-1">
               <h4>3D Models</h4>
               <p>Portray real-world and conceptual visuals for art, entertainment, simulation and drafting.</p>
             </a>
           </li>
           <li class="nav-item mt-2" data-aos="fade-up" data-aos-delay="100">
             <a class="nav-link" data-toggle="tab" href="#tab-2">
               <h4>3D Characters</h4>
               <p>Creates a three-dimensional digital representation of a surface or an object.</p>
             </a>
           </li>
           <li class="nav-item mt-2" data-aos="fade-up" data-aos-delay="200">
             <a class="nav-link" data-toggle="tab" href="#tab-3">
               <h4>AR | VR | XR | MR</h4>
               <p>Real and/or virtual environments or interactions generated by tech.</p>
             </a>
           </li>
           <li class="nav-item mt-2" data-aos="fade-up" data-aos-delay="300">
             <a class="nav-link" data-toggle="tab" href="#tab-4">
               <h4>3D Scan</h4>
               <p>Creating high-precision 3D models of real-world objects</p>
             </a>
           </li>
           <li class="nav-item mt-2" data-aos="fade-up" data-aos-delay="300">
             <a class="nav-link" data-toggle="tab" href="#tab-5">
               <h4>Brand Design</h4>
               <p>Creating a visual identity for a company or product</p>
             </a>
           </li>
         </ul>
       </div>
       <div class="col-lg-6 order-1 order-lg-2" data-aos="zoom-in">
         <div class="tab-content">
           <div class="tab-pane active show" id="tab-1">
             <figure>
               <div class="card-container">
                 <div class="img">
                   <img src="<?php echo get_template_directory_uri(); ?>/assets/img/services/Final.png" alt="Image Description">
                 </div>

                 <ul class="horizontal-list">
                   <li>Furniture Modeling</li>
                   <li>Product Modeling</li>
                   <li>Kitchen Appliances</li>
                   <li>Low Poly Modeling</li>
                   <li>High Poly Baking</li>
                   <li>Cosmetic</li>
                 </ul>
               </div>

             </figure>
           </div>
           <div class="tab-pane" id="tab-2">
             <figure>
               <div class="card-container">
                 <div class="img">
                   <img src="<?php echo get_template_directory_uri(); ?>/assets/img/services/tbrender_edited.jpg" alt="Image Description">
                 </div>

                 <ul class="horizontal-list">
                   <li>Animation ready 3D Model</li>
                   <li>Game Ready Character</li>
                   <li>Low Poly Model</li>
                   <li>NFT Characters</li>
                   <li>PBR Texturing</li>
                   <li>Anime Characters</li>
                   <li>Animals</li>
                   <li>2D to 3D</li>
                 </ul>
               </div>
             </figure>
           </div>
           <div class="tab-pane" id="tab-3">
             <figure>
               <div class="card-container">
                 <div class="img">
                   <img src="<?php echo get_template_directory_uri(); ?>/assets/img/services/Untitled_00000_edited.png" alt="Image Description">
                 </div>

                 <ul class="horizontal-list">
                   <li>3D Model WebAR</li>
                   <li>NFT</li>
                   <li>Fashion</li>
                   <li>Architectural</li>
                   <li>VR Ready Game Assets</li>
                   <li>AR Ready 3D Models</li>
                   <li>PBR Models</li>
                 </ul>
               </div>
             </figure>
           </div>
           <div class="tab-pane" id="tab-4">
             <figure>
               <div class="card-container">
                 <div class="img">
                   <img src="<?php echo get_template_directory_uri(); ?>/assets/img/services/Skull copy.png" alt="Image Description">
                 </div>

                 <ul class="horizontal-list">
                   <li>Shoes Scans PP</li>
                   <li>Shoes re-topology</li>
                   <li>Human Scan PP</li>
                   <li>Furniture Scan PP</li>
                   <li>3D Print Ready Models</li>
                   <li>3D Game Ready Models</li>
                 </ul>
               </div>
             </figure>
           </div>

           <div class="tab-pane" id="tab-5">
             <figure>
               <div class="card-container">
                 <div class="img">
                   <img src="<?php echo get_template_directory_uri(); ?>/assets/img/services/Stationery_Mockup_1K.png" alt="Image Description">
                 </div>

                 <ul class="horizontal-list">
                   <li>Logo Designing</li>
                   <li>Mock-up</li>
                   <li>Cloth Design</li>
                   <li>Flyers</li>
                   <li>Brochure Design</li>
                   <li>Visiting Card</li>
                   <li>Book Cover</li>
                 </ul>
               </div>
             </figure>
           </div>
         </div>
       </div>
     </div>

   </div>
 </section><!-- End Features Section -->


 <!-- ======= Cta Section ======= -->
 <div class="service-CTA">
   <section id="cta" class="cta">
     <div class="container">

       <!-- <div class="row" data-aos="zoom-in">
        <div class="col-lg-7 text-center text-lg-left">
          <h3>We are Designer</h3>
          <p> Our portfolio showcases our team's expertise and creativity, highlighting our commitment to delivering high-quality 3D assets, immersive AR/VR experiences, and cutting-edge 3D scanning services.</p>
        </div>
        <div class="col-lg-4 cta-btn-container text-center">
        <model-viewer src="<?php echo get_template_directory_uri() ?>/MetaSpeed_Shoe_Sample_3.glb" camera-controls auto-rotate style="width: 650px; height: 500px;" exposure="1.0" shadow-intensity="1.5" shadow-offset="5" background-color="#f0f0f0" shadow-softness="0.5" loading="lazy" disable-zoom></model-viewer>
        </div>
      </div> -->

     </div>
   </section>
 </div>

 <!-- End Cta Section -->


 <div class="container mt-5" id="service_container">
   <div class="row mb-5">
     <div class="col-lg-12">
       <h2 class="text-center">WORK PROCESS</h2>
     </div>
   </div>
   <div class="row">
     <div class="col-lg-6 mb-4">
       <div class="card">
         <div class="card-body">

           <div class="icon"><i class="fas fa-search mr-2" style="color: #28a745;"></i></div>
           <div class="icon_content">
             <h5 class="card-title">Research</h5>
             <p class="card-text">Research on 3D refers to the study and development of 3D technologies, tools, and techniques for various applications.</p>
           </div>
         </div>
       </div>
     </div>
     <div class="col-lg-6 mb-4">
       <div class="card">
         <div class="card-body">

           <div class="icon"><i class="fas fa-lightbulb mr-2" style="color: #dc3545;"></i></div>
           <div class="icon_content">
             <h5 class="card-title">Concept</h5>
             <p class="card-text">Concept 3D refers to the initial visualization stage of creating a 3D model or project, where ideas and concepts are translated into rough 3D representations.</p>
           </div>
         </div>
       </div>
     </div>
     <div class="col-lg-6 mb-4">
       <div class="card">
         <div class="card-body">

           <div class="icon"><i class="fas fa-cubes mr-2" style="color: #ffc107;"></i></div>
           <div class="icon_content">
             <h5 class="card-title">Develop</h5>
             <p class="card-text">Creating 3D representations of objects or environments using specialized software and techniques.</p>
           </div>
         </div>
       </div>
     </div>
     <div class="col-lg-6 mb-4">
       <div class="card">
         <div class="card-body">

           <div class="icon"><i class="fas fa-paint-brush mr-2" style="color: #17a2b8;"></i></div>
           <div class="icon_content">
             <h5 class="card-title">Style It</h5>
             <p class="card-text">Insert your style description here.</p>
           </div>
         </div>
       </div>
     </div>
   </div>
 </div>



 <style>
   #service_container.container {
     display: flex;
     flex-direction: column;
     justify-content: center;
     padding-bottom: 6%;
   }

   .card {
     transition: all 0.3s ease;
     border: none;
     height: calc(100% + 20px);
     /* Adjust the value as needed */
   }

   .card:hover {
     transform: translateY(-5px);
     box-shadow: 0 4px 8px rgb(0 0 0 / 35%);
   }

   .card-body {
     background-color: #6c757d1a;
     height: 100%;
     padding: 11px 11px 11px 24px;
     margin: 30px;
     border-radius: 33px;
     display: flex;
   }

   .card-title {
     margin-bottom: 0;
   }

   i.fas {
     font-size: 5rem;
     padding: 16px 26px 0px 0px;
     /* line-height: 25px; */
   }

   .card-body .icon {
     padding-top: 11px;
   }

   .card-body .icon_content {
     padding-top: 11px;
   }
   .text-center {
    font-size: 3rem;
    text-align: center!important;
}
.card-title {
    margin-bottom: 0;
    font-weight: 700;
}

   /* Responsive top margin */
   /* @media (min-width: 768px) {
  .mt-md-5 {
    margin-top: 7rem !important;
  }
}

@media (min-width: 992px) {
  .mt-lg-5 {
    margin-top: 7rem !important;
  }
}

@media (min-width: 1200px) {
  .mt-xl-5 {
    margin-top: 7rem !important;
  }
} */
 </style>

 <?php get_footer(); ?>